version: '3.8'

services:
  web:
    build: .
    container_name: shop_container
    # ports:  <-- ПРИБИРАЄМО! Flask тепер доступний тільки для Nginx всередині мережі
    #   - "5000:5000"
    env_file:
      - .env
    volumes:
      - sqlite_data:/app/data
      - static_volume:/app/static # Ділимося папкою static з Nginx
    restart: unless-stopped
    # Додаємо healthcheck згідно з вимогами
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  nginx:
    image: nginx:alpine
    container_name: shop_nginx
    ports:
      - "80:80" # Тепер вхід через порт 80 (стандартний для вебу)
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # Наш конфіг
      - static_volume:/app/static # Nginx бере картинки звідси
    depends_on:
      - web # Nginx запуститься тільки після Flask
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  sqlite_data:
  static_volume: # Новий том для статики
