version: '3.8'

services:
  web:
    build: .
    container_name: shop_container
    ports:
      - "5000:5000"  # Прокинути порт 5000 на хості до 5000 в контейнері
    env_file:
      - .env         # Підвантаження змінних середовища
    volumes:
      - sqlite_data:/app/data  # Volume для збереження бази даних між перезапусками
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  sqlite_data:
